vincent-peugnet/wcms

public/w/index.php
voilà comme ça ça fonctionne chez moi, si ça fonctionne pas chez toi c'est qu'il doit y avoir un problème avec apache
=> utilisation d'un chemin relatif pour les inclusions

assets/js/edit.js
Hello The ctrl + s inconsistent save should be fixed with this commit !
=> fix for ctrl + s inconsistent save action

app/view/templates/edittopbar.php, assets/js/edit.js
Yo, I added the <kbd>ctrl</kbd> + <kbd>D</kbd> keyboard shortcut to open the display page.
Closes #9
=> add display shortcut with ctrl + d

package-lock.json, package.json, src/edit.js, webpack.config.js
As the Js part of the project is a little bit like my part I want to improve my comfort by adding a prettier auto-format at each build. This way I don't have to think about the formatting style
=> style: add prettier on webpack build

.default.env, Makefile, README.md, package.json
- run npm and composer only when needed
- include .default.env
- add watch targets
- `make all` builds in dev mode, `make dist` in prod mode
=> perf: make optimizations

assets/css/home.css, src/home.js
a little css fix for the submenus + a click outside a submenu closes it
=> Feat: better submenus

src/home.js
sorry, just a small fix for the previous pull request
=> fix: only close the submenus of the menubar

app/view/templates/media.php, src/fn/fn.js, src/media.js, webpack.config.js
This adds in media the same js features as in home
=> feat: media js bundle with checkall and closesubmenus

MANUAL.md
=> correcting manual

app/class/Modelrender.php
``````markdown
prout
<https://club1.fr>
<a href="https://club1.fr">https://club1.fr</a>
<a href="https://club1.fr">https://club1.fr!</a>
`https://club1.fr`
`<https://club1.fr>`
```
echo test # <https://club1.fr>
```
echo test # <https://club1.fr>
echo test # https://club1.fr
https://club1.fr
un [article]
un lien [manuel](https://club1.fr)
un lien [manuel vers https://club1.fr!](https://club1.fr)
``````
<p>prout</p>
<p><a  class="external" target="_blank" href="https://club1.fr"><a href="https://club1.fr" class="external"  target="_blank" >club1.fr</a></a></p>
<p><a  class="external" target="_blank" href="https://club1.fr"><a href="https://club1.fr" class="external"  target="_blank" >club1.fr</a></a></p>
<p><a  class="external" target="_blank" href="https://club1.fr"><a …
=> fix links rewrting in code blocks

assets/css/edit.css, src/edit.js, webpack.config.js
=> feat: Coloration for W synthax in CodeMirror

Makefile, phpcs.xml, phpunit.xml
There was some problems left in the checks config
=> tests: fix setup of phpcsand phpunit

.github/workflows/php.yml, README.md
For coverage to work you will need to sign in [coveralls](https://coveralls.io) **using your github account** and then add your wcms repo in coveralls **before merging this pull request**.
This other thing that's added is annotations on github pull requests by parsing the report files of the test suite.
=> Add reports and coverage

.github/matchers/phpcs.json, .github/matchers/phpstan.json, .github/matchers/phpunit.json, .github/workflows/php.yml, Makefile, README.md, app/class/Colors.php, app/class/Controller.php, app/class/Controlleradmin.php, app/class/Controllerconnect.php, app/class/Controllermedia.php, app/class/Controllerpage.php, app/class/Dbitem.php, app/class/Event.php, app/class/Flywheel/Formatter/JSON.php, app/class/Item.php, app/class/Media.php, app/class/Modelhome.php, app/class/Modelmedia.php, app/class/Modelpage.php, app/class/Modelrender.php, app/class/Modeltimeline.php, app/class/Page.php, app/class/User.php, app/fn/fn.php, phpcs.xml
Add problem matchers for phpcs, phpstan and phpunit.
Add composer cache
Test over multiple php version
Also fix a lot of phpstan detected errors
Here is an example of what this does
https://github.com/n-peugnet/wcms/commit/657f115c3af98d697cf32737fdff04901adc460a
=> tests(ci): problemMatchers, 3 php versions, optims

README.md, app/class/Config.php, app/class/Controlleruser.php, app/class/Media.php, app/class/User.php, composer.json, composer.lock, index.php
Add whoops as a development tool to pretty print all errors in dev. This makes catching `Throwable` instead of `Exception` acceptable in `index.php`.
=> Add whoops

.github/workflows/php.yml, Makefile, app/class/Logger.php, index.php, tests/FilesTest.php, tests/LoggerTest.php
Add MacOS and Windows tests to GitHub actions. For the tests to work everywhere I had to make some fixes
=> Tests multiple os

package-lock.json, package.json
update npm dependencies to fix vulnerabilities. Overrides #125
=> chore(deps): npm update

Makefile
and also use more precise zip -d command to make sure only unwanted files are deleted
=> fix: remove codecov.yaml from dist

Makefile, composer.json, composer.lock, phpunit.xml, tests/LoggerTest.php
- set composer platform to 7.4 as this is the oldest version supported
- run composer update phpunit/phpunit --with-all-dependencies
- update deprecated code in tests
- correctly set XDebug mode for phpunit coverage
- update phpunit.xml to latest schema
=> deps: upgrade phpunit from 8 to 9

LICENSE
- extends copyright dates
- add myself as an author
=> update copyright notice

.github/workflows/checks.yml
Let's see if it passes on GitHub.
=> Test with newer PHP versions in CI

.gitignore
=> Add back build dir to .gitignore

src/media.js
Add support for Drag and drop files within the media panel.
A progressive enhancement that triggers the regular file upload field, by filling it with dropped files.
=> Drag and drop to upload

assets/css/theme/soy-n-wasabi.css
New theme for more spicy sushi: soy n’ wasabi!
=> Soynwasabi
