vincent-peugnet/wcms

.gitignore, README.md, app/view/templates/edit.php, app/view/templates/edittabs.php, app/view/templates/edittopbar.php, app/view/templates/layout.php, assets/css/edit.css, assets/js/edit.js, package-lock.json, package.json, src/edit.js, webpack.config.js
Hey I started to implement this feature
Left to do:
Closes #11
=> Include CodeMirror in edit page

README.md, composer.json, composer.lock
Fix warning about outdated lock by setting the correct PHP required version and then regenerating the lock.
=> Fix composer warning about outdated lock

app/view/templates/edit.php, src/edit.js
Added only asterix. You can easily edit the `changed()` and `saved()` functions to try the emoticon change.
Part of #17
=> feat: add unsaved changes' asterix indicator

app/class/Header.php, app/class/Modelrender.php, app/class/Summary.php
This PR fixes 2 issues I had with the SUMMARY of W-cms (#80 and #81)
The summary rendering is not entirely valid yet as `<ul>` element shouldn't be inside `<p>` element. But this is more complicated to fix and browsers fixes it automatically (this is not an excuse, it should still be fixed).
=> Fix summary rendering

src/edit.js
=> fix: un-highlight wsyntax in comments

Makefile, composer.json, composer.lock, phpcs.xml
I added a [phpcs](https://github.com/squizlabs/PHP_CodeSniffer) config with a minimal PSR12 config. I let you run the formater yourself so you can adjust the configuration dy adding or removing some rules. Both are accessible in the `vendor/bin` folder. And I also added a `check` target to make that runs all the tests (only phpcs for now).
I recommend that you install [this very good vscode extension](https://marketplace.visualstudio.com/items?itemName=wongjn.php-sniffer) that registers **phpcs** as a Linter and **phpcbf** as a Formater. Then you just have to add the following to you vscode settings.json
```json
"phpSniffer.autoDetect": true
```
=> tests: add phpcs with minimal PSR12 config

Makefile, README.md, composer.json, composer.lock, phpcs.xml, phpunit.xml, tests/SummaryTest.php
This adds [PHPUnit](https://phpunit.de/) with coverage reports.
The [PHPUnit Test Explorer extension](https://marketplace.visualstudio.com/items?itemName=recca0120.vscode-phpunit) is useful to run tests interdependently and o visualize the coverage in VSCode you can use the [coverage gutters extension](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters)
As we discussed it would be good to move `fn.php` in a class in `app/class` this way it can be auto-loaded by composer and more easily tested in PHPUnit
=> tests: add phpunit w/coverage + 1 test SummaryTest

.github/workflows/php.yml, .gitignore, Makefile, README.md, app/class/Controller.php, app/class/Controllermedia.php, app/class/Logger.php, app/class/Modelrender.php, app/class/Routes.php, composer.json, composer.lock, index.php, phpstan.neon, tests/FilesTest.php, tests/LoggerTest.php
Once again there is a [vscode extension for phpstan](https://marketplace.visualstudio.com/items?itemName=Mandy91.vscode-phpstan). The only problem with it is that it doesn't read the level from the config file so you have to set it in vscode config:
```json
"phpstan.level": "5"
```
I add a phpstan extension for phpunit (I don't remember exactly what it adds). And also another one more important that checks all the Exception stuff, which is great. But there is one more thing to understand about exceptions. It's quite well explained on te [extension github repo](https://github.com/pepakriz/phpstan-exception-rules#motivation).
This is because of this Exception extension that I added  fb4eca8 and daec2ee. The first one is an exemple of refactoring that transform an `Exception` into a …
=> Add phpstan

app/class/Page.php
html classes or ids can contain uppercase characters
=> fix(render): css was strtolower-ed

.github/workflows/php.yml, Makefile, app/class/Bookmark.php, app/class/Colors.php, app/class/Controller.php, app/class/Controllerfont.php, app/class/Controllerhome.php, app/class/Controllermedia.php, app/class/Controllerpage.php, app/class/Controlleruser.php, app/class/Item.php, app/class/Media.php, app/class/Model.php, app/class/Modeladmin.php, app/class/Modelfont.php, app/class/Modelhome.php, app/class/Modelmedia.php, app/class/Modelrender.php, app/class/Quickcss.php, app/class/Routes.php, app/fn/fn.php, codecov.yaml, composer.json, composer.lock
This is to fix the github build:
- drop php 7.2
- run composer update
- add `make fix` target that runs `phpcbf`
- add info about `make fix` in `make lint`
- run `make fix`
You should remove `test php 7.2 / ubuntu-latest` from the required checks now that it is dropped
=> build(deps): fix github ci

app/class/Config.php
- update default values returned by get_class_vars,
otherwise domain is never correctly set
- use more robust scheme detection
This bug seems to have appeared with the upgrade from php7.2 to php7.4
=> fix: init config script

app/class/Modelrender.php
This class is IMO not usefull as we already have the img selector to
select all the medias in the page (or we can even select img and a).
On the other hand, adding this class overrides the ones we can add with
markdown extra's syntax: {.custom-class}.
=> fix(render): remove added media class

Makefile
- make each command depend on vendor
- fix lint failing with recent bash versions
=> fix: make checks

index.php
there is no help about it in the migration doc : https://github.com/getsentry/sentry-php/blob/master/UPGRADE-3.0.md
=> fix: remove old sentry option

app/view/templates/edittopbar.php
I'm often using <kbd>ctrl</kbd> + <kbd>s</kbd>, <kbd>ctrl</kbd> + <kbd>d</kbd> to quickly display the result of my changes. But by doing this a new tab is opened each time.
This change makes the browser reuse the same tab each time the display button is clicked
=> feat: reuse the same tab for each click on display

src/edit.js
allows to differentiate between network error:
and http error (example with [`http_response_code(409)`](https://www.php.net/manual/en/function.http-response-code.php) in the controller):
=> feat: catch http errors and display error

app/class/Controllerpage.php
So I replaced all `$id` parameters in `Controllerpage.php` with `$page` wich is the one used in all the routes. I changed it there instead of in the routes, as the variable name of the route is also used everywhere `router->generate()` is called.
=> fix: controllers must use route's variables' names since PHP8

.github/workflows/checks.yml, Makefile, phpstan.neon
- ci: use more make, to make sure scripts run locally using make pass the CI correctly
- ci: add PHP 8.1 to tests and phpstan
- fix: phpstan config for php 8.0+ by removing useless config
=> ci: fix and test phpstan with php 8.0+

app/class/Servicerss.php
Based on the default language value and the page's own language value.
[RFC4287 section 2](https://datatracker.ietf.org/doc/html/rfc4287#section-2):
> Any element defined by this specification MAY have an xml:lang
> attribute, whose content indicates the natural language for the
> element and its descendents.  The language context is only
> significant for elements and attributes declared to be "Language-
> Sensitive" by this specification.
The validity of the resulting document has been tested using <https://validator.w3.org/feed/>.
=> rss: add xml:lang attributes to englobing elements

package-lock.json, package.json, src/sentry.js
This should fix some vulnerabilities in NPM dependencies and also brings down the number of packages from 207 to 179.
I tried to make sure that all dependencies are compatible with your version of Nodejs, but you should test that it is still building on your computer before merging.
=> Upgrade npm dependencies

app/class/Optlist.php
- Use config lang if page's lang is empty
- use current page's lang instead of individal pages from the list's lang
- Optimize rendering by creating the formatter only once before the start of the loop instead of for each page of the list.
Fix: date formatter in rendered LIST does not fall back to config's lang
Fix: title of rendered LIST elements use current page's date
(Already applied on club1.fr)
=> Rework Optlist date formatting in render

.github/workflows/checks.yml, tests/ServicerenderTest.php
This should fix the currently failing builds for MacOS, and prevent future builds from failing the same way.
Let's see...
=> Fix ICU version in CI to 71.1

Makefile, package-lock.json, package.json
Version 5 has a breaking change and needs another option to build each entrypoint separately. This option may be removed in the future and building assets separately does not allow to deduplicate code between multiple entrypoints, so the build script is changed to build all the assets together in a simple step.
=> build: upgrade webpack-cli, stop building js assets separately

.github/workflows/checks.yml
see: <https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/>
=> update set-output usage

app/class/Servicesession.php
To make sure no warning is emitted.
=> Always use the null coalescent operator in servicesession

src/edit.js
This allow to stay at the same place in the previewed page after the render refresh. For now it is only working with Ctrl + D, not when clicking the button, as the button is only a simple link. Later the button could be overriden with javascript to allow the same behaviour
=> Reload preview window instead of changing location

Makefile
This should allow to reduce a little the size of the release tarball.
```diff
$ diff -u --color before.txt after.txt 
--- before.txt	2024-06-12 19:05:35.956518382 +0200
+++ after.txt	2024-06-12 19:06:07.864593362 +0200
@@ -250,7 +251,6 @@
adding: vendor/firebase/php-jwt/src/JWT.php (deflated 74%)
adding: vendor/jamesmoss/ (stored 0%)
adding: vendor/jamesmoss/flywheel/ (stored 0%)
-  adding: vendor/jamesmoss/flywheel/.scrutinizer.yml (deflated 31%)
adding: vendor/jamesmoss/flywheel/composer.json (deflated 44%)
adding: vendor/jamesmoss/flywheel/LICENSE (deflated 41%)
adding: vendor/jamesmoss/flywheel/src/ (stored 0%)
@@ -272,15 +272,12 @@
adding: vendor/jamesmoss/flywheel/src/JamesMoss/Flywheel/Formatter/JSON.php (deflated 47%)
adding: …
```
=> Exclude dependencies' hidden files from release tarball

app/view/templates/admin.php, app/view/templates/alertcommandnotfound.php, app/view/templates/alertexistnot.php, app/view/templates/alertlayout.php, app/view/templates/alertnotpublished.php, app/view/templates/alertprivate.php, app/view/templates/backtopbar.php, app/view/templates/connect.php, app/view/templates/delete.php, app/view/templates/edit.php, app/view/templates/editleftbar.php, app/view/templates/editrightbar.php, app/view/templates/edittabs.php, app/view/templates/edittopbar.php, app/view/templates/forbidden.php, app/view/templates/home.php, app/view/templates/homebookmark.php, app/view/templates/homemenu.php, app/view/templates/homeopt.php, app/view/templates/layout.php, app/view/templates/macro_tablesort.php, app/view/templates/media.php, app/view/templates/mediamenu.php, app/view/templates/user.php, app/view/templates/userconfirmdelete.php
Switching templates logic style to if:else:endif and foreach:endforeach. 
The first commit did no re-indentation, but for some files, I felt necessary to do some (which lead to quite complex diffs).
=> Switching templates logic style 

.github/workflows/checks.yml, Makefile
Before this, absolutely no automated checks were done on template files now we at least ensure that they are valid PHP files.
The parallel run should work correctly on macOS and other Unix-like systems. On Windows, we fallback to sequential execution.
This takes around 1 second on my not so fast 2/4 cores Intel laptop.
=> Add parallel PHP syntax check on template files

app/view/templates/homemenu.php, app/view/templates/mediamenu.php, assets/css/base.css, src/fn/fn.js
- remove home specific absolute positioning
- remove unused "hide in case of js" css
@jbidoret : this is how I would do it.
You tell me if it's ok for you ! 😃
I don't see the problem when only the button is `display:none`. 🤔 maybe because I did'nt checked all the themes!
Anyway, since with this PR, `<form>` is always inside a `hbar-section`, it can be hidden without breaking the flex positioning.
=> workspace menu is always in hbar-section, fix #480

app/class/Config.php, app/class/Controllerconnect.php, app/class/Controllerprofile.php, app/class/Controlleruser.php, app/class/Modelbookmark.php, app/class/Modelclub1ldap.php, app/class/Modelldap.php, app/class/User.php, app/view/templates/admin.php, app/view/templates/forbidden.php, app/view/templates/profile.php, app/view/templates/user.php
it's not even a plugin.
It's directly inside, in the core. 🫀
Corresponding issue: #237
=> Ldap auth feature
